name: Push workflows
on: [push]
permissions:
  contents: read

jobs:
  test-lint-and-build:
    name: Test, lint and build
    runs-on: xcode-27

    steps:
      - name: Check out repository
        uses: actions/checkout@v7

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Lint
        run: swiftlint Sources Tests

      - name: Build
        run: swift build --configuration release

      - name: Test
        run: swift test

      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: Release Build
          archive: false
          path: |
            .build/release/sz
